//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evaluation_", Namespace="http://schemas.datacontract.org/2004/07/MoodWcfService.Entities")]
    public partial class Evaluation_ : object
    {
        
        private int EvaluationIdField;
        
        private int ExperienceField;
        
        private decimal MoodRatingField;
        
        private int PriceField;
        
        private int RestaurantIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EvaluationId
        {
            get
            {
                return this.EvaluationIdField;
            }
            set
            {
                this.EvaluationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Experience
        {
            get
            {
                return this.ExperienceField;
            }
            set
            {
                this.ExperienceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoodRating
        {
            get
            {
                return this.MoodRatingField;
            }
            set
            {
                this.MoodRatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RestaurantId
        {
            get
            {
                return this.RestaurantIdField;
            }
            set
            {
                this.RestaurantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvaluationServiceReference.IEvaluationService")]
    public interface IEvaluationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationService/GetAllEvaluations", ReplyAction="http://tempuri.org/IEvaluationService/GetAllEvaluationsResponse")]
        System.Threading.Tasks.Task<EvaluationServiceReference.Evaluation_[]> GetAllEvaluationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationService/GetEvaluationById", ReplyAction="http://tempuri.org/IEvaluationService/GetEvaluationByIdResponse")]
        System.Threading.Tasks.Task<EvaluationServiceReference.Evaluation_> GetEvaluationByIdAsync(string evalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationService/CreateEvaluation", ReplyAction="http://tempuri.org/IEvaluationService/CreateEvaluationResponse")]
        System.Threading.Tasks.Task<bool> CreateEvaluationAsync(EvaluationServiceReference.Evaluation_ evaluation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationService/EditEvaluation", ReplyAction="http://tempuri.org/IEvaluationService/EditEvaluationResponse")]
        System.Threading.Tasks.Task<bool> EditEvaluationAsync(EvaluationServiceReference.Evaluation_ evaluation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationService/DeleteEvaluation", ReplyAction="http://tempuri.org/IEvaluationService/DeleteEvaluationResponse")]
        System.Threading.Tasks.Task<bool> DeleteEvaluationAsync(EvaluationServiceReference.Evaluation_ evaluation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IEvaluationServiceChannel : EvaluationServiceReference.IEvaluationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class EvaluationServiceClient : System.ServiceModel.ClientBase<EvaluationServiceReference.IEvaluationService>, EvaluationServiceReference.IEvaluationService
    {
        
        public EvaluationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EvaluationServiceReference.Evaluation_[]> GetAllEvaluationsAsync()
        {
            return base.Channel.GetAllEvaluationsAsync();
        }
        
        public System.Threading.Tasks.Task<EvaluationServiceReference.Evaluation_> GetEvaluationByIdAsync(string evalId)
        {
            return base.Channel.GetEvaluationByIdAsync(evalId);
        }
        
        public System.Threading.Tasks.Task<bool> CreateEvaluationAsync(EvaluationServiceReference.Evaluation_ evaluation)
        {
            return base.Channel.CreateEvaluationAsync(evaluation);
        }
        
        public System.Threading.Tasks.Task<bool> EditEvaluationAsync(EvaluationServiceReference.Evaluation_ evaluation)
        {
            return base.Channel.EditEvaluationAsync(evaluation);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEvaluationAsync(EvaluationServiceReference.Evaluation_ evaluation)
        {
            return base.Channel.DeleteEvaluationAsync(evaluation);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
